### ISSUE TITLE
Initial portal config validation error

### ISSUE THREAD

**Issue by gmcintire** [SonarSoftwareInc/customer_portal#3] opened 2019-04-30 20:44 UTC
Location:
Immediately after installing via docker instructions and visiting portal.domain.name/settings

Problem:
Leaving any fields out that will throw a validation error (such as email settings) result in flash messages after being redirected to / (not /settings), thereby losing anything previously entered in config.

**Comment by SonarSoftware** [comment] 2019-04-30 20:47
@zulandar Please take a look at this one too.

**Comment by gmcintire** [comment] 2019-04-30 20:53
Additional bug: when returning to the settings screen after initial config, making no changes, and submitting will always delete the custom logo.

**Comment by zulandar** [comment] 2019-04-30 21:27
@gmcintire I have tested the first issue with only setting application URL and ticketing settings. (leaving email settings blank). and when I click save both in Chrome/Firebox I get the validation error flash message and the settings I set are still in the fields. I've tried this from a fresh install as well.

I am still looking at the custom logo

**Comment by zulandar** [comment] 2019-05-01 18:55
@gmcintire can you attempt to reproduce this issue? 

This may of been resolved with the JS fixes as of right now I am not able to reproduce the issue within DO or locally.

**Comment by zulandar** [comment] 2019-05-02 19:04
Resolved in PR #2

**Closed** 2019-05-02 19:04 UTC
Labels: bug
