### ISSUE TITLE
sonar-customerportal container fails to answer responses after a few hours

### ISSUE THREAD

**Issue by gmcintire** [SonarSoftwareInc/customer_portal#14] opened 2019-05-21 14:24 UTC
I have not been able to accurately reproduce this to see what's causing it yet. It could be a watchtower pull causes it to not restart properly, or something else is happening. All of the other containers continue to work properly, with nginx returning 504 errors. Manually restarting the container or rebooting the system results in normal functionality again. 

These are the last few lines from the container log:

```sonar-customerportal | [Sat May 18 14:42:39.740156 2019] [mpm_prefork:notice] [pid 47] AH00163: Apache/2.4.25 (Debian) PHP/7.3.3 configured -- resuming normal operations
sonar-customerportal | [Sat May 18 14:42:39.740252 2019] [core:notice] [pid 47] AH00094: Command line: 'apache2 -D FOREGROUND'
sonar-customerportal | [Sat May 18 21:01:21.551430 2019] [mpm_prefork:error] [pid 47] AH00161: server reached MaxRequestWorkers setting, consider raising the MaxRequestWorkers setting
```

**Comment by SonarSoftware** [comment] 2019-05-21 15:51
@geneccx Do we even need Apache in here? Seems like we should be able to handle it all with nginx, although we'd have to migrate the CSP and other config.

**Comment by gmcintire** [comment] 2019-05-21 16:06
Some additional information: it could be a memory leak in the container. I've been watching memory usage on the container and it's been slowly creeping up without ever going down over the past few hours.

**Comment by zulandar** [comment] 2019-05-21 16:41
@gmcintire could you provide a rough estimate on how many hours before it crash's? What are the resources you've allocated to the host?

**Comment by geneccx** [comment] 2019-05-21 17:04
> @geneccx Do we even need Apache in here? Seems like we should be able to handle it all with nginx, although we'd have to migrate the CSP and other config.

We don't strictly need Apache in there, but I suspect the underlying issue is due to fpm workers hanging and not getting killed somehow. However, I wonder why the execution limit isn't automatically killing them. It's a bit hard to troubleshoot at this point without getting this consistently reproducible.

**Comment by gmcintire** [comment] 2019-05-21 18:20
> @gmcintire could you provide a rough estimate on how many hours before it crash's? What are the resources you've allocated to the host?

I'm running it on a VM with 8GB ram, resource exhaustion isn't the issue. It looks like it happens anywhere from every 6-19 hours and has happened on 2 different VPS providers, as well as my own server it's on now with more ram. On a VPS with 2gb ram or less and no swap it'll crash the whole machine.

It happens on a regular basis, so I'd be happy to run any commands or do extra debugging to help. I have Pingdom checking the root url once a minute, which could be causing the fpm workers to pile up.

**Comment by gmcintire** [comment] 2019-05-21 20:37
It just went down again -- I started it when I posted the original post. It's currently using 933MB for just sonar-customerportal. Looking at the processes, there are probably 100-150 forks of ``` apache2 -DFOREGROUND``` running from within that container right now.

**Comment by geneccx** [comment] 2019-05-21 20:39
Thanks for the update. Anything of note in the Apache logs?

**Comment by gmcintire** [comment] 2019-05-21 20:41
Nope, it just stops responding to any requests until it's restarted.

**Comment by gmcintire** [comment] 2019-05-23 01:43
You can manually trigger the crash with ab every time:

```ab -t 150 https://portal.url.here/```

Before the test completes apache will have forked too many times and stop responding.

**Comment by zulandar** [comment] 2019-05-23 02:34
@gmcintire after some testing with PR #15 looks like this issue is resolved. We still have some internal testing before we merge the test and update the docker image.

**Comment by gmcintire** [comment] 2019-05-23 03:23
👍

**Comment by zulandar** [comment] 2019-05-23 03:48
@gmcintire this issue is resolved within master branch. If you currently have the portal up and running you will need to follow the upgrade guide on the wiki - [Upgrade Guide](https://github.com/SonarSoftwareInc/customer_portal/wiki/Update-guide)

**Closed** 2019-05-23 03:48 UTC
Labels: bug
